[phases.setup]
nixPkgs = ["php82", "composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan config:cache && php artisan migrate --force && apache2-foreground"
