[phases.setup]
pkgs = ["php82", "php82-cli", "php82-mbstring", "php82-xml", "php82-bcmath", "php82-pdo_mysql", "php82-tokenizer", "php82-openssl", "composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan config:clear && php -S 0.0.0.0:$PORT -t public"
